nmMode: hardlinks-local
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.1.cjs
npmRegistryServer: "https://registry.npmjs.org"
# npmScopes:
#   monymonydev:
#     npmAlwaysAuth: true
#     # TODO: populate env variable properly
#     npmAuthToken: "${MONYMONY_GITHUB_AUTH_TOKEN}"
#     npmRegistryServer: "https://npm.pkg.github.com"
